{"version":1,"ops":[{"type":1,"author":{"id":"e733efee4a6bea946b6c8ca979ad3c5d1d5b66cb"},"timestamp":1563861480,"metadata":{"gitlab-base-url":"https://gitlab.com/","gitlab-id":"289","gitlab-project-id":"6581209","gitlab-url":"https://gitlab.com/langurmonkey/gaiasky/-/issues/289","origin":"gitlab"},"title":"py4j.protocol.Py4JNetworkError An error occurred while trying to connect to the Java server (127.0.0.1:25333)","message":"Hi. I have been following your super cool project Gaia-Sky, and have found \"issue\" \nwith Connection to GateWay from Python(2-3), port is closed.\n\nIs it bug or do i need configure extra server ?\nin the file global.properties i have set property \"program.restport=25333\"\n\n```\ntoor@abi:scripts$ lsb_release -a\nNo LSB modules are available.\nDistributor ID:\tDebian\nDescription:\tDebian GNU/Linux 9.9 (stretch)\nRelease:\t9.9\nCodename:\tstretch\n```\n\n```\ntoor@abi:scripts$ uname -a\nLinux abi 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux\n```\n\n![Screenshot_at_2019-07-23_07-28-09](/uploads/5e07b97e825a169e104ddadc400e780d/Screenshot_at_2019-07-23_07-28-09.png)![Splashscreen-version](/uploads/1dd83b5f772bc8289123f4e536ec1eb4/Splashscreen-version.png)\n\nps: Python (2/3) ...","files":null}]}