{"version":1,"ops":[{"type":1,"author":{"id":"26b298c8d0a0b958a6462737e597b4d8106bb40f"},"timestamp":1533639021,"metadata":{"gitlab-base-url":"https://gitlab.com/","gitlab-id":"281","gitlab-project-id":"6581209","gitlab-url":"https://gitlab.com/langurmonkey/gaiasky/-/issues/281","origin":"gitlab"},"title":"GaiaSky does not start under Windows if username contains non-ascii character","message":"System: Windows 10 Pro (1803) 64-bit\n\nGaiaSkay: 64-bit version 2.0.2\n\n\"gaiasky.exe\" is terminated immediately after starting the program.\n\nThe error log shows:\n```\nconsole: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.\nTraceback (most recent call last):\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\site.py\", line 585, in \u003cmodule\u003e\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\site.py\", line 567, in main\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\site.py\", line 300, in addusersitepackages\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\site.py\", line 289, in getusersitepackages\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\sysconfig.py\", line 416, in get_path\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\sysconfig.py\", line 407, in get_paths\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\sysconfig.py\", line 180, in _expand_vars\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\sysconfig.py\", line 154, in _subst_vars\n  File \"E:\\Programme\\GaiaSky\\lib\\jython-standalone-2.7.0.jar\\Lib\\sysconfig.py\", line 154, in _subst_vars\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xfc' in position 10: ordinal not in range(128)\n```\n\nReason for the failure is a **Windows username containing a non-ascii character**, in\nthis case a German umlaut (\\xfc = Ã¼). Running the program under an account without \numlauts works without any problems.\n\nConcerning the first line in the error log \"console: Failed ...\": \nTo get around, the following line must be added to gaiasky.vmoptions:\n`-Dpython.console.encoding=UTF-8`\n\nsee: http://bugs.jython.org/issue2222","files":null}]}